//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CREG.Analitica.AWS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class concepto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public concepto()
        {
            this.concepto1 = new HashSet<concepto>();
            this.concepto_formato = new HashSet<concepto_formato>();
        }
    
        public decimal id_concepto { get; set; }
        public string cod_concepto { get; set; }
        public Nullable<decimal> id_concepto_padre { get; set; }
        public string descripcion_concepto { get; set; }
        public int nivel_concepto { get; set; }
        public Nullable<decimal> id_tipo_concepto { get; set; }
        public Nullable<int> id_naturaleza_concepto { get; set; }
        public Nullable<bool> flag_ref_normativa { get; set; }
        public bool concepto_cargado { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public string usuario_actualizacion { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<concepto> concepto1 { get; set; }
        public virtual concepto concepto2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<concepto_formato> concepto_formato { get; set; }
        public virtual naturaleza_concepto naturaleza_concepto { get; set; }
        public virtual tipo_concepto tipo_concepto { get; set; }
    }
}
