//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CREG.Analitica.AWS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class formato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public formato()
        {
            this.concepto_formato = new HashSet<concepto_formato>();
            this.edc_formato = new HashSet<edc_formato>();
            this.historial_aom = new HashSet<historial_aom>();
        }
    
        public decimal id_formato { get; set; }
        public string cod_formato { get; set; }
        public string nombre_formato { get; set; }
        public Nullable<bool> flag_formato_div { get; set; }
        public Nullable<int> tipo_formato { get; set; }
        public decimal id_actividad { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
        public string usuario_actualizacion { get; set; }
        public bool activo { get; set; }
    
        public virtual actividad actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<concepto_formato> concepto_formato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edc_formato> edc_formato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historial_aom> historial_aom { get; set; }
    }
}
