//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CREG.Analitica.AWS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_aom
    {
        public decimal id_historial_aom { get; set; }
        public decimal id_empresa { get; set; }
        public Nullable<decimal> id_formato { get; set; }
        public string id_tramo { get; set; }
        public string nombre_original_archivo_aom { get; set; }
        public string nombre_archivo_aom { get; set; }
        public Nullable<int> anio_aom { get; set; }
        public string extension_aom { get; set; }
        public string tamanio_aom { get; set; }
        public string usuario_carga { get; set; }
        public System.DateTime fecha_carga { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public string ruta_aom { get; set; }
        public string error { get; set; }
        public string estado { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual formato formato { get; set; }
        public virtual tramo tramo { get; set; }
    }
}
