//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CREG.Analitica.AWS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_auditoria
    {
        public long id_log { get; set; }
        public string tabla { get; set; }
        public long id_registro_tabla { get; set; }
        public string columna_afectada { get; set; }
        public string valor_antiguo { get; set; }
        public string valor_nuevo { get; set; }
        public System.DateTime fecha { get; set; }
        public string usuario { get; set; }
    }
}
