//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CREG.Analitica.AWS.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CREG_Analitica_AWSEntities : DbContext
    {
        public CREG_Analitica_AWSEntities()
            : base("name=CREG_Analitica_AWSEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 180;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accion> accion { get; set; }
        public virtual DbSet<actividad> actividad { get; set; }
        public virtual DbSet<concepto> concepto { get; set; }
        public virtual DbSet<concepto_formato> concepto_formato { get; set; }
        public virtual DbSet<edc> edc { get; set; }
        public virtual DbSet<edc_formato> edc_formato { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<formato> formato { get; set; }
        public virtual DbSet<log_auditoria> log_auditoria { get; set; }
        public virtual DbSet<naturaleza_concepto> naturaleza_concepto { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<tipo_accion> tipo_accion { get; set; }
        public virtual DbSet<tipo_concepto> tipo_concepto { get; set; }
        public virtual DbSet<tramo> tramo { get; set; }
        public virtual DbSet<permiso> permiso { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<role_permiso> role_permiso { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<empresa_actividad> empresa_actividad { get; set; }
        public virtual DbSet<historial_aom> historial_aom { get; set; }
    }
}
