//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CREG.Analitica.AWS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_permiso
    {
        public long id_role_permiso { get; set; }
        public long id_role { get; set; }
        public long id_permiso { get; set; }
        public bool activo { get; set; }
    
        public virtual permiso permiso { get; set; }
        public virtual role role { get; set; }
    }
}
