//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CREG.Analitica.AWS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EMPRE_APPAOM
    {
        public Nullable<decimal> COD_EMPRESA { get; set; }
        public Nullable<decimal> NIT_EMPRESA { get; set; }
        public Nullable<decimal> DIV_NIT_EMPRESA { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string SIGLA_EMPRESA { get; set; }
        public Nullable<decimal> COD_SUI_EMPRESA { get; set; }
    }
}
